import { test, expect } from '@playwright/test'
import { signUp, signIn, signOut, createBuilder, uid } from './helpers'

test('bid → award → PO accepted by sub → sub bills → builder pays; budget', async ({ page }) => {
  test.setTimeout(180_000)
  const id = uid()
  const ownerEmail = `bea.${id}@bids.test`
  const subEmail = `fran.${id}@framing.test`
  await signUp(page, { first: 'Bea', last: 'Builder', email: ownerEmail })
  await createBuilder(page, `Bid Homes ${id}`)
  await page.goto('/jobs/new')
  await page.getByLabel('Job name').fill(`Aspen ${id}`)
  await page.getByRole('button', { name: 'Create job' }).click()
  await expect(page.getByRole('heading', { name: `Aspen ${id}` })).toBeVisible()

  await page.goto('/settings/subs')
  await page.getByRole('button', { name: 'Add sub or vendor' }).click()
  await page.getByLabel('Company name').fill(`Frame Co ${id}`)
  await page.getByLabel('Email').fill(subEmail)
  await page.getByRole('button', { name: 'Add', exact: true }).click()
  await expect(page.getByText(`Frame Co ${id} added`)).toBeVisible()
  await page.keyboard.press('Escape')
  const link = await page.locator('[data-copy*="/invite/"]').first().getAttribute('data-copy')

  // Bid package
  await page.goto('/bids/new')
  await page.getByLabel('Title').fill('Framing labour')
  await page.getByLabel('Scope of work').fill('Frame house per A-101 to A-105.')
  await page.getByRole('button', { name: 'Create bid package' }).click()
  await expect(page.getByRole('heading', { name: 'Framing labour' })).toBeVisible()
  await page.getByRole('button', { name: 'Add line' }).click()
  await page.getByLabel('Line title').fill('Main floor framing')
  await page.getByRole('button', { name: 'Add line' }).click()
  await page.getByLabel('Line title').last().fill('Roof sheathing')
  await page.getByLabel('Quantity').last().fill('100')
  await page.getByLabel('Unit', { exact: true }).last().fill('sheet')
  await page.getByRole('button', { name: 'Save lines' }).click()
  await expect(page.getByText('Lines saved.')).toBeVisible()
  await page.getByLabel(`Frame Co ${id}`).check()
  await page.getByRole('button', { name: 'Save bidders' }).click()
  await expect(page.getByLabel(`Frame Co ${id}`)).toBeChecked()
  await page.getByRole('button', { name: 'Send to bidders' }).click()
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByText('Open for bids')).toBeVisible()
  const bidUrl = page.url()
  await signOut(page)

  // Sub joins and bids
  await page.goto(new URL(link!).pathname)
  await page.getByRole('link', { name: 'Create account' }).click()
  await page.getByLabel('First name').fill('Fran')
  await page.getByLabel('Last name').fill('Framer')
  await page.getByLabel('Password').fill('correct-horse-battery')
  await page.getByRole('button', { name: 'Create account' }).click()
  await page.getByRole('button', { name: 'Accept invite' }).click()
  await expect(page).toHaveURL(/\/summary/)
  await page.goto('/bids')
  await expect(page.getByText(`Bid Homes ${id}`)).toBeVisible()
  await page.getByRole('link', { name: 'Framing labour' }).click()
  await page.getByLabel('Unit price for Main floor framing').fill('5000')
  await page.getByLabel('Unit price for Roof sheathing').fill('30')
  await expect(page.getByTestId('bid-total')).toHaveText('$8,000.00')
  await page.getByRole('button', { name: 'Submit bid' }).click()
  await expect(page.getByText('Bid submitted.')).toBeVisible()
  await signOut(page)

  // Builder awards → PO → send
  await signIn(page, ownerEmail)
  await page.goto(bidUrl)
  await expect(page.getByTestId(`bid-total-Frame Co ${id}`)).toHaveText('$8,000.00')
  await page.getByRole('button', { name: 'Award' }).click()
  await page.getByRole('button', { name: 'Award', exact: true }).last().click()
  await expect(page).toHaveURL(/\/purchase-orders\//)
  await expect(page.getByTestId('lines-total')).toHaveText('$8,000.00')
  await page.getByRole('button', { name: 'Send to sub' }).click()
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByText('Awaiting acceptance')).toBeVisible()
  const poUrl = page.url()
  await signOut(page)

  // Sub accepts and bills
  await signIn(page, subEmail)
  await page.goto(poUrl)
  await page.getByLabel(/I agree that my electronic signature/).check()
  await page.getByRole('button', { name: 'Accept and sign' }).click()
  await expect(page.getByText('Accepted', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Submit a bill' }).click()
  await page.getByLabel('Your invoice number').fill('FC-1001')
  await page.getByLabel('Amount for Main floor framing').fill('2500')
  await expect(page.getByTestId('bill-payable')).toHaveText('$2,375.00')   // 2500 + 125 GST − 250 holdback
  await page.getByRole('button', { name: 'Submit bill' }).click()
  await expect(page.getByRole('heading', { name: 'Invoice FC-1001' })).toBeVisible()
  await expect(page.getByText('Needs approval')).toBeVisible()
  await signOut(page)

  // Builder approves and pays
  await signIn(page, ownerEmail)
  await page.goto('/notifications')
  await expect(page.getByText(`New bill from Frame Co ${id}`)).toBeVisible()
  await page.goto('/bills')
  await page.getByRole('link', { name: 'FC-1001' }).click()
  await page.getByRole('button', { name: 'Approve' }).click()
  await expect(page.getByText('Approved', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Record \$2,375\.00 paid/ }).click()
  await expect(page.getByText('Paid', { exact: true }).first()).toBeVisible()
  await expect(page.getByTestId('bill-amount')).toHaveText('$2,375.00')

  await page.goto(poUrl)
  await expect(page.getByTestId('holdback-balance')).toHaveText('$250.00')
  await page.goto('/budget')
  await expect(page.getByTestId('budget-committed')).toHaveText('$8,000.00')
  await expect(page.getByTestId('budget-actual')).toHaveText('$2,500.00')
  await page.screenshot({ path: 'test-results/95-budget.png', fullPage: true })
})
