import { test, expect } from '@playwright/test'
import { signUp, signIn, signOut, createBuilder, uid } from './helpers'

test('change order: price, release, client draws signature, client requests a change', async ({ page }) => {
  const id = uid()
  const ownerEmail = `cora.${id}@co.test`
  const clientEmail = `owner.${id}@home.test`
  await signUp(page, { first: 'Cora', last: 'Change', email: ownerEmail })
  await createBuilder(page, `Change Homes ${id}`)

  await page.goto('/settings/company')
  await page.getByLabel('Can request change orders').check()
  await page.getByRole('button', { name: 'Save defaults' }).click()
  await expect(page.getByText('Client portal defaults saved.')).toBeVisible()

  await page.goto('/jobs/new')
  await page.getByLabel('Job name').fill(`Cedar ${id}`)
  await page.getByRole('button', { name: 'Create job' }).click()
  await expect(page.getByRole('heading', { name: `Cedar ${id}` })).toBeVisible()
  await page.getByLabel('First name').fill('Omar')
  await page.getByLabel('Last name').fill('Owner')
  await page.locator('#c_email').fill(clientEmail)
  await page.getByRole('button', { name: 'Add client' }).click()
  const invite = page.locator('[data-copy*="/invite/"]').first()
  await expect(invite).toBeVisible()
  const link = await invite.getAttribute('data-copy')

  // Builder prices a change
  await page.goto('/change-orders/new')
  await page.getByLabel('Title').fill('Add pot lights')
  await page.getByLabel('Description (client sees this)').fill('Six LED pot lights in the kitchen ceiling.')
  await page.getByRole('button', { name: 'Create change order' }).click()
  await expect(page.getByRole('heading', { name: 'Add pot lights' })).toBeVisible()
  await page.getByRole('button', { name: 'Add line' }).click()
  await page.getByLabel('Line title').fill('LED pot light')
  await page.getByLabel('Quantity').fill('6')
  await page.getByLabel('Unit cost').fill('50')
  await page.getByRole('button', { name: 'Add line' }).click()
  await page.getByLabel('Line title').last().fill('Electrician')
  await page.getByLabel('Quantity').last().fill('4')
  await page.getByLabel('Unit cost').last().fill('90')
  await page.getByLabel('Markup type').last().selectOption('amount')
  await page.getByLabel('Markup', { exact: true }).last().fill('40')
  await page.getByRole('button', { name: 'Save lines' }).click()
  await expect(page.getByText('Saved.')).toBeVisible()
  await expect(page.getByTestId('co-total')).toHaveText('$798.00')
  await page.getByRole('button', { name: 'Release to client' }).click()
  await page.getByRole('button', { name: 'Release', exact: true }).click()
  await expect(page.getByText('Awaiting approval').first()).toBeVisible()
  await signOut(page)

  // Client signs by drawing, then requests another change
  await page.goto(new URL(link!).pathname)
  await page.getByRole('link', { name: 'Create account' }).click()
  await page.getByLabel('First name').fill('Omar')
  await page.getByLabel('Last name').fill('Owner')
  await page.getByLabel('Password').fill('correct-horse-battery')
  await page.getByRole('button', { name: 'Create account' }).click()
  await page.getByRole('button', { name: 'Accept invite' }).click()
  await expect(page).toHaveURL(/\/summary/)
  await page.goto('/change-orders')
  await page.getByRole('link', { name: 'Add pot lights' }).click()
  await expect(page.getByTestId('co-total')).toHaveText('$798.00')
  await page.getByRole('button', { name: 'Draw signature' }).click()
  const pad = page.getByLabel('Signature pad')
  await pad.scrollIntoViewIfNeeded()
  const box = (await pad.boundingBox())!
  await page.mouse.move(box.x + 20, box.y + 60)
  await page.mouse.down()
  for (let i = 1; i <= 12; i++) await page.mouse.move(box.x + 20 + i * 25, box.y + 60 + (i % 2 ? 25 : -20))
  await page.mouse.up()
  await page.getByLabel(/I agree that my electronic signature/).check()
  await page.getByRole('button', { name: 'Approve and sign' }).click()
  await expect(page.getByRole('img', { name: 'Signature of Omar Owner' })).toBeVisible()
  await page.screenshot({ path: 'test-results/70-co-signed.png', fullPage: true })

  await page.goto('/change-orders/new')
  await page.getByLabel('Title').fill('Bigger deck')
  await page.getByLabel('What would you like to change?').fill('Can we make the deck 16x20?')
  await page.getByRole('button', { name: 'Send request' }).click()
  await expect(page.getByText('Your builder is reviewing this request.')).toBeVisible()
  await signOut(page)

  // Builder sees the request and the approved total
  await signIn(page, ownerEmail)
  await page.goto('/notifications')
  await expect(page.getByText('Change requested: Bigger deck')).toBeVisible()
  await page.goto('/change-orders')
  await expect(page.getByText('Requested', { exact: true })).toBeVisible()
  await expect(page.getByText('$798.00').first()).toBeVisible()
})
