import { test, expect } from '@playwright/test'
import { signUp, signOut, signIn, createBuilder, uid } from './helpers'

const inDays = (n: number) => new Date(Date.now() + n * 86_400_000).toISOString().slice(0, 10)

test('compliance: sub files WCB clearance with a document; builder sees status and rules', async ({ page }) => {
  test.setTimeout(120_000)
  const id = uid()
  const ownerEmail = `cam.${id}@comply.test`
  await signUp(page, { first: 'Cam', last: 'Comply', email: ownerEmail })
  await createBuilder(page, `Comply Homes ${id}`)
  await page.goto('/settings/subs')
  await page.getByRole('button', { name: 'Add sub or vendor' }).click()
  await page.getByLabel('Company name').fill(`Roof Co ${id}`)
  await page.getByLabel('Email').fill(`rita.${id}@roof.test`)
  await page.getByRole('button', { name: 'Add', exact: true }).click()
  await expect(page.getByText(`Roof Co ${id} added`)).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('row', { name: new RegExp(`Roof Co ${id}`) }).getByText('Missing documents')).toBeVisible()
  const link = await page.locator('[data-copy*="/invite/"]').first().getAttribute('data-copy')
  await signOut(page)

  // Sub joins and files its WCB clearance
  await page.goto(new URL(link!).pathname)
  await page.getByRole('link', { name: 'Create account' }).click()
  await page.getByLabel('First name').fill('Rita')
  await page.getByLabel('Last name').fill('Roofer')
  await page.getByLabel('Password').fill('correct-horse-battery')
  await page.getByRole('button', { name: 'Create account' }).click()
  await page.getByRole('button', { name: 'Accept invite' }).click()
  await expect(page).toHaveURL(/\/summary/)
  await page.goto('/settings/compliance')
  await expect(page.getByRole('heading', { name: `For Comply Homes ${id}` })).toBeVisible()
  await page.getByLabel('Number').fill('WCB-7731')
  await page.getByLabel('Provider').fill('WCB Alberta')
  await page.getByLabel('Expires').fill(inDays(12))
  await page.getByRole('button', { name: 'Add certificate' }).click()
  await expect(page.getByText('WCB clearance letter saved.')).toBeVisible()
  await page.getByRole('button', { name: 'Upload', exact: true }).click()
  await page.getByLabel('Choose files').setInputFiles({ name: 'wcb-clearance.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\n%%EOF\n') })
  await page.getByRole('dialog').getByRole('button', { name: 'Upload', exact: true }).click()
  await expect(page.getByRole('link', { name: 'wcb-clearance.pdf' })).toBeVisible()
  await page.getByLabel('Certificate').selectOption('liability_insurance')
  await page.getByLabel('Number').fill('CGL-22')
  await page.getByLabel('Coverage (insurance)').fill('$2,000,000')
  await page.getByLabel('Expires').fill(inDays(200))
  await page.getByRole('button', { name: 'Add certificate' }).click()
  await expect(page.getByText('Commercial general liability saved.')).toBeVisible()
  await expect(page.getByText('Expiring soon')).toBeVisible()
  await signOut(page)

  // Builder sees the documents and the status
  await signIn(page, ownerEmail)
  await page.goto('/settings/subs')
  await expect(page.getByRole('row', { name: new RegExp(`Roof Co ${id}`) }).getByText('Expiring soon')).toBeVisible()
  await page.getByLabel('Block payments to subs with missing or expired documents').check()
  await page.getByRole('button', { name: 'Save rules' }).click()
  await expect(page.getByText('Compliance rules saved.')).toBeVisible()
  await page.getByRole('link', { name: `Roof Co ${id}` }).click()
  await expect(page.getByText('WCB-7731')).toBeVisible()
  await expect(page.getByText('$2,000,000.00')).toBeVisible()
  const doc = page.getByRole('link', { name: 'wcb-clearance.pdf' })
  const res = await page.request.get((await doc.getAttribute('href'))!)
  expect(res.status()).toBe(200)
})
