import { test, expect } from '@playwright/test'
import { signUp, createBuilder, uid } from './helpers'

test('job templates: save a job as a template, start a new job from it with shifted dates', async ({ page }) => {
  test.setTimeout(120_000)
  const id = uid()
  await signUp(page, { first: 'Tess', last: 'Template', email: `tess.${id}@tpl.test` })
  await createBuilder(page, `Template Homes ${id}`)
  await page.goto('/jobs/new')
  await page.getByLabel('Job name').fill(`Show home ${id}`)
  await page.getByLabel('Projected start').fill('2026-11-02')
  await page.getByRole('button', { name: 'Create job' }).click()
  await expect(page.getByRole('heading', { name: `Show home ${id}` })).toBeVisible()

  await page.goto('/todos/new')
  await page.getByLabel('Title').fill('Order windows')
  await page.getByLabel('Due date').fill('2026-11-04')
  await page.getByLabel('Checklist').fill('Confirm sizes\nPlace order')
  await page.getByRole('button', { name: 'Create to-do' }).click()
  await expect(page.getByRole('heading', { name: 'Order windows' })).toBeVisible()
  await page.goto('/plans/specs/new')
  await page.getByLabel('Division').fill('Finishes')
  await page.getByLabel('Title').fill('Standard paint')
  await page.getByLabel('Specification').fill('Eggshell, two coats')
  await page.getByRole('button', { name: 'Create specification' }).click()
  await expect(page).toHaveURL(/\/plans\/specs\/[0-9a-f-]{36}/)

  // Save as template
  await page.goto('/jobs')
  await page.getByRole('link', { name: `Show home ${id}` }).click()
  await page.getByRole('button', { name: 'Save as template' }).click()
  await page.getByLabel('Template name').fill(`Bungalow ${id}`)
  await page.getByRole('button', { name: 'Save template' }).click()
  await expect(page.getByRole('heading', { name: `Bungalow ${id}` })).toBeVisible()
  await expect(page.getByText('Template', { exact: true })).toBeVisible()
  await page.goto('/jobs')
  await expect(page.getByRole('link', { name: `Bungalow ${id}` })).toHaveCount(0)
  await page.getByRole('tab', { name: 'Templates' }).click()
  await expect(page.getByRole('link', { name: `Bungalow ${id}` })).toBeVisible()

  // New job from the template, four months later
  await page.getByRole('link', { name: `Bungalow ${id}` }).click()
  await page.getByRole('link', { name: 'New job from template' }).click()
  await expect(page.getByLabel('Template', { exact: true })).toHaveValue(/[0-9a-f-]{36}/)
  await page.getByLabel('Job name').fill(`Lot 7 ${id}`)
  await page.getByLabel('Projected start').fill('2027-03-01')
  await page.getByRole('button', { name: 'Create job' }).click()
  await expect(page.getByRole('heading', { name: `Lot 7 ${id}` })).toBeVisible()
  await page.goto('/search?q=Order%20windows')
  await page.locator('li', { hasText: `Lot 7 ${id}` }).getByRole('link', { name: 'Order windows' }).click()
  await expect(page.getByText('Mar 3, 2027')).toBeVisible()
  await expect(page.getByText('Place order')).toBeVisible()
  await page.goto('/plans?tab=specs')
  await expect(page.getByRole('link', { name: 'Standard paint' })).toBeVisible()
})
