import { test, expect } from '@playwright/test'
import { signUp, signIn, signOut, createBuilder, uid } from './helpers'

test('RFI round trip between builder and sub', async ({ page }) => {
  const id = uid()
  const ownerEmail = `rob.${id}@alpha.test`
  const subEmail = `plumb.${id}@plumb.test`
  await signUp(page, { first: 'Rob', last: 'Rfi', email: ownerEmail })
  await createBuilder(page, `RFI Homes ${id}`)
  await page.goto('/jobs/new')
  await page.getByLabel('Job name').fill(`Poplar ${id}`)
  await page.getByRole('button', { name: 'Create job' }).click()
  await expect(page.getByRole('heading', { name: `Poplar ${id}` })).toBeVisible()
  const jobUrl = page.url()

  await page.goto('/settings/subs')
  await page.getByRole('button', { name: 'Add sub or vendor' }).click()
  await page.getByLabel('Company name').fill(`Flow Plumbing ${id}`)
  await page.getByLabel('Email').fill(subEmail)
  await page.getByRole('button', { name: 'Add', exact: true }).click()
  await expect(page.getByText(`Flow Plumbing ${id} added`)).toBeVisible()
  await page.keyboard.press('Escape')
  const link = await page.locator('[data-copy*="/invite/"]').first().getAttribute('data-copy')
  await page.goto(jobUrl)
  await Promise.all([page.waitForResponse((r) => r.request().method() === 'POST' && r.url().includes('/jobs/')), page.getByRole('button', { name: 'Add to job' }).click()])

  await page.goto('/todos/new')
  await page.getByLabel('Title').fill('Rough-in plumbing')
  await page.getByRole('button', { name: 'Create to-do' }).click()
  await expect(page.getByRole('heading', { name: 'Rough-in plumbing' })).toBeVisible()

  await page.goto('/rfis/new')
  await page.locator('#title').fill('Tub drain location')
  await page.getByLabel('Assignee').selectOption({ label: `Flow Plumbing ${id}` })
  await page.getByLabel('Question').fill('Plans show the tub drain 6" off the wall. Confirm before rough-in?')
  await page.getByLabel('Related record').selectOption({ label: 'Rough-in plumbing' })
  await page.getByRole('button', { name: 'Send' }).click()
  await expect(page.getByRole('heading', { name: 'Tub drain location' })).toBeVisible()
  await expect(page.getByText('Sent', { exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Rough-in plumbing' })).toBeVisible()
  await signOut(page)

  await page.goto(new URL(link!).pathname)
  await page.getByRole('link', { name: 'Create account' }).click()
  await page.getByLabel('First name').fill('Pat')
  await page.getByLabel('Last name').fill('Plumb')
  await page.getByLabel('Password').fill('correct-horse-battery')
  await page.getByRole('button', { name: 'Create account' }).click()
  await page.getByRole('button', { name: 'Accept invite' }).click()
  await expect(page).toHaveURL(/\/summary/)
  await page.goto('/rfis')
  await page.getByRole('button', { name: /All active jobs/ }).click()
  await page.getByRole('link', { name: 'Tub drain location' }).click()
  await page.getByLabel('Write a response').fill('Confirmed, 6" off finished wall.')
  await page.getByRole('button', { name: 'Post response' }).click()
  await expect(page.locator('li', { hasText: 'Confirmed, 6" off finished wall.' })).toBeVisible()
  await page.getByRole('button', { name: 'Mark complete' }).click()
  await expect(page.getByText('Completed', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Reopen' })).toHaveCount(0)
  await page.screenshot({ path: 'test-results/50-rfi-sub.png', fullPage: true })
  await signOut(page)

  await signIn(page, ownerEmail)
  await expect(page.getByRole('link', { name: /Notifications, \d+ unread/ })).toBeVisible()
  await page.goto('/notifications')
  await expect(page.getByText('New response on RFI #1: Tub drain location')).toBeVisible()
  await page.screenshot({ path: 'test-results/51-notifications.png', fullPage: true })
  await page.getByRole('button', { name: 'Mark all read' }).click()
  await expect(page.getByRole('link', { name: 'Notifications', exact: true })).toBeVisible()
  await page.goto('/rfis')
  await page.getByRole('link', { name: 'Tub drain location' }).click()
  await page.getByRole('button', { name: 'Reopen' }).click()
  await expect(page.getByText('Reopened', { exact: true })).toBeVisible()
})
