import { test, expect } from '@playwright/test'
import { signUp, signIn, signOut, createBuilder, uid } from './helpers'

test('selection with allowance: client chooses, builder approves into a change order', async ({ page }) => {
  const id = uid()
  const ownerEmail = `sam.${id}@sel.test`
  const clientEmail = `pat.${id}@home.test`
  await signUp(page, { first: 'Sam', last: 'Select', email: ownerEmail })
  await createBuilder(page, `Select Homes ${id}`)
  await page.goto('/jobs/new')
  await page.getByLabel('Job name').fill(`Maple ${id}`)
  await page.getByRole('button', { name: 'Create job' }).click()
  await expect(page.getByRole('heading', { name: `Maple ${id}` })).toBeVisible()
  await page.getByLabel('First name').fill('Pat')
  await page.getByLabel('Last name').fill('Home')
  await page.locator('#c_email').fill(clientEmail)
  await page.getByRole('button', { name: 'Add client' }).click()
  const invite = page.locator('[data-copy*="/invite/"]').first()
  await expect(invite).toBeVisible()
  const link = await invite.getAttribute('data-copy')

  await page.goto('/selections/new')
  await page.getByLabel('Title').fill('Kitchen backsplash')
  await page.getByLabel('Category').fill('Tile')
  await page.getByLabel('Location').fill('Kitchen')
  await page.getByLabel('Allowance').fill('1000')
  await page.getByLabel('Deadline', { exact: true }).selectOption('date')
  await page.getByLabel('Deadline date').fill('2026-12-15')
  await page.getByRole('button', { name: 'Create selection' }).click()
  await expect(page.getByRole('heading', { name: 'Kitchen backsplash' })).toBeVisible()

  await page.getByLabel('Choice title').fill('White subway tile')
  await page.getByLabel('Client price').fill('900')
  await page.getByRole('button', { name: 'Add choice' }).click()
  await expect(page.getByRole('heading', { name: 'White subway tile' })).toBeVisible()
  await page.getByLabel('Choice title').fill('Zellige')
  await page.getByLabel('Vendor').fill('Stone Tile Co')
  await page.getByLabel('Client price').fill('1450')
  await page.getByLabel('Builder cost').fill('1100')
  await page.getByRole('button', { name: 'Add choice' }).click()
  await expect(page.getByRole('heading', { name: 'Zellige' })).toBeVisible()
  await expect(page.getByText('Builder cost $1,100.00')).toBeVisible()
  await page.getByRole('button', { name: 'Release to client' }).click()
  await expect(page.getByText('Awaiting choice')).toBeVisible()
  await signOut(page)

  await page.goto(new URL(link!).pathname)
  await page.getByRole('link', { name: 'Create account' }).click()
  await page.getByLabel('First name').fill('Pat')
  await page.getByLabel('Last name').fill('Home')
  await page.getByLabel('Password').fill('correct-horse-battery')
  await page.getByRole('button', { name: 'Create account' }).click()
  await page.getByRole('button', { name: 'Accept invite' }).click()
  await expect(page).toHaveURL(/\/summary/)
  await page.goto('/selections')
  await page.getByRole('link', { name: 'Kitchen backsplash' }).click()
  await expect(page.getByText('Builder cost')).toHaveCount(0)
  await page.locator('[data-choice="Zellige"]').getByRole('button', { name: 'Choose this' }).click()
  await expect(page.getByText(/Selected: Zellige for \$1,450\.00 \(\$450\.00 over the allowance\)/)).toBeVisible()
  await page.screenshot({ path: 'test-results/80-selection-client.png', fullPage: true })
  await signOut(page)

  await signIn(page, ownerEmail)
  await page.goto('/notifications')
  await expect(page.getByText('Selection made: Kitchen backsplash')).toBeVisible()
  await page.goto('/selections')
  await expect(page.getByText('$450.00')).toBeVisible()
  await page.getByRole('link', { name: 'Kitchen backsplash' }).click()
  await expect(page.getByLabel(/Create a change order for the \$450\.00 overage/)).toBeChecked()
  await page.getByRole('button', { name: 'Approve selection' }).click()
  await expect(page.getByRole('heading', { name: 'Selection: Kitchen backsplash' })).toBeVisible()
  await expect(page.getByLabel('Line title')).toHaveValue('Allowance overage: Zellige')
  await expect(page.getByTestId('co-total')).toHaveText('$472.50')
})
