import { test, expect } from '@playwright/test'
import { signUp, signIn, signOut, createBuilder, uid } from './helpers'

test('submittal: request → sub submits → revise → resubmit → approved', async ({ page }) => {
  test.setTimeout(150_000)
  const id = uid()
  const ownerEmail = `sue.${id}@sm.test`
  const subEmail = `wes.${id}@windows.test`
  await signUp(page, { first: 'Sue', last: 'Submittal', email: ownerEmail })
  await createBuilder(page, `Submittal Homes ${id}`)
  await page.goto('/jobs/new')
  await page.getByLabel('Job name').fill(`Fir ${id}`)
  await page.getByRole('button', { name: 'Create job' }).click()
  await expect(page.getByRole('heading', { name: `Fir ${id}` })).toBeVisible()
  const jobUrl = page.url()
  await page.goto('/settings/subs')
  await page.getByRole('button', { name: 'Add sub or vendor' }).click()
  await page.getByLabel('Company name').fill(`Window Co ${id}`)
  await page.getByLabel('Email').fill(subEmail)
  await page.getByRole('button', { name: 'Add', exact: true }).click()
  await expect(page.getByText(`Window Co ${id} added`)).toBeVisible()
  await page.keyboard.press('Escape')
  const link = await page.locator('[data-copy*="/invite/"]').first().getAttribute('data-copy')
  await page.goto(jobUrl)
  await Promise.all([page.waitForResponse((r) => r.request().method() === 'POST' && r.url().includes('/jobs/')), page.getByRole('button', { name: 'Add to job' }).click()])

  await page.goto('/submittals/new')
  await page.getByLabel('Title').fill('Window shop drawings')
  await page.getByLabel('Spec section').fill('08 50 00')
  await page.getByLabel('Submitted by (sub)').selectOption({ label: `Window Co ${id}` })
  await page.getByRole('button', { name: 'Save and request from sub' }).click()
  await expect(page.getByRole('heading', { name: 'Window shop drawings' })).toBeVisible()
  await expect(page.getByText(`Ball in court: Window Co ${id}`)).toBeVisible()
  const url = page.url()
  await signOut(page)

  await page.goto(new URL(link!).pathname)
  await page.getByRole('link', { name: 'Create account' }).click()
  await page.getByLabel('First name').fill('Wes')
  await page.getByLabel('Last name').fill('Window')
  await page.getByLabel('Password').fill('correct-horse-battery')
  await page.getByRole('button', { name: 'Create account' }).click()
  await page.getByRole('button', { name: 'Accept invite' }).click()
  await expect(page).toHaveURL(/\/summary/)
  await page.goto(url)
  await page.getByLabel('Submission notes').fill('Elevations and sections attached.')
  await page.getByRole('button', { name: 'Submit for review' }).click()
  await expect(page.getByText('Ball in court: Sue Submittal')).toBeVisible()
  await signOut(page)

  await signIn(page, ownerEmail)
  await page.goto(url)
  await page.getByLabel('Decision').selectOption('revise')
  await page.getByRole('button', { name: 'Save review' }).click()
  await expect(page.getByText('Add review notes for that decision.')).toBeVisible()
  await page.getByLabel('Review notes').fill('Show the sill detail at the patio door.')
  await page.getByRole('button', { name: 'Save review' }).click()
  await expect(page.getByText('Revise and resubmit · rev 0')).toBeVisible()
  await signOut(page)

  await signIn(page, subEmail)
  await page.goto(url)
  await page.getByLabel('Submission notes').fill('Sill detail added on sheet 4.')
  await page.getByRole('button', { name: 'Submit for review' }).click()
  await expect(page.getByText('In review · rev 1')).toBeVisible()
  await signOut(page)

  await signIn(page, ownerEmail)
  await page.goto(url)
  await page.getByLabel('Decision').selectOption('approved')
  await page.getByRole('button', { name: 'Save review' }).click()
  await expect(page.getByText('Approved · rev 1')).toBeVisible()
})
