import { test, expect } from '@playwright/test'
import { signUp, signOut, createBuilder, uid } from './helpers'

test('builder assigns a to-do to a sub; the sub completes it', async ({ page }) => {
  const id = uid()
  const subEmail = `trim.${id}@trim.test`
  await signUp(page, { first: 'Tara', last: 'Todo', email: `tara.${id}@alpha.test` })
  await createBuilder(page, `Todo Homes ${id}`)
  await page.goto('/jobs/new')
  await page.getByLabel('Job name').fill(`Spruce ${id}`)
  await page.getByRole('button', { name: 'Create job' }).click()
  await expect(page.getByRole('heading', { name: `Spruce ${id}` })).toBeVisible()
  const jobUrl = page.url()

  await page.goto('/settings/subs')
  await page.getByRole('button', { name: 'Add sub or vendor' }).click()
  await page.getByLabel('Company name').fill(`Trim Pros ${id}`)
  await page.getByLabel('Email').fill(subEmail)
  await page.getByRole('button', { name: 'Add', exact: true }).click()
  await expect(page.getByText(`Trim Pros ${id} added`)).toBeVisible()
  await page.keyboard.press('Escape')
  const link = await page.locator('[data-copy*="/invite/"]').first().getAttribute('data-copy')
  await page.goto(jobUrl)
  await page.getByRole('button', { name: 'Add to job' }).click()

  await page.goto('/todos/new')
  await page.getByLabel('Title').fill('Install baseboards main floor')
  await page.getByLabel('Priority').selectOption('high')
  await page.getByLabel(`Trim Pros ${id}`).check()
  await page.getByLabel('Checklist').fill('Cut and fit\nNail and fill')
  await page.getByRole('button', { name: 'Create to-do' }).click()
  await expect(page.getByRole('heading', { name: 'Install baseboards main floor' })).toBeVisible()
  await page.getByLabel('Write a comment').fill('Materials are in the garage')
  await page.getByLabel('Share with subs').check()
  await page.getByRole('button', { name: 'Post comment' }).click()
  await expect(page.locator('li', { hasText: 'Materials are in the garage' })).toBeVisible()
  await page.screenshot({ path: 'test-results/30-todo.png', fullPage: true })
  await signOut(page)

  // Sub joins and completes
  await page.goto(new URL(link!).pathname)
  await page.getByRole('link', { name: 'Create account' }).click()
  await page.getByLabel('First name').fill('Tim')
  await page.getByLabel('Last name').fill('Trim')
  await page.getByLabel('Password').fill('correct-horse-battery')
  await page.getByRole('button', { name: 'Create account' }).click()
  await page.getByRole('button', { name: 'Accept invite' }).click()
  await expect(page).toHaveURL(/\/summary/)
  await page.goto('/todos')
  await page.getByRole('button', { name: /All active jobs/ }).click()
  await expect(page.getByRole('link', { name: 'Install baseboards main floor' })).toBeVisible()
  await page.screenshot({ path: 'test-results/31-sub-todos.png', fullPage: true })
  await page.getByRole('link', { name: 'Install baseboards main floor' }).click()
  await expect(page.getByText('Materials are in the garage')).toBeVisible()
  await expect(page.getByRole('checkbox', { name: 'Mark complete' })).toBeDisabled()
  const post = () => page.waitForResponse((r) => r.request().method() === 'POST' && r.url().includes('/todos/'))
  await Promise.all([post(), page.getByLabel('Cut and fit').check()])
  await Promise.all([post(), page.getByLabel('Nail and fill').check()])
  await page.reload()
  await expect(page.getByText('2 of 2 done')).toBeVisible()
  await Promise.all([post(), page.getByRole('checkbox', { name: 'Mark complete' }).check()])
  await page.reload()
  await expect(page.getByText('Complete', { exact: true })).toBeVisible()
})
